[build]
builder = "NIXPACKS"
buildCommand = "cd /opt && sudo wget https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz && sudo tar -xvzf keycloak-$KEYCLOAK_VERSION.tar.gz && sudo mv keycloak-$KEYCLOAK_VERSION /opt/keycloak"
nixpacksPlan = {"providers":["...","java"]}

[deploy]
numReplicas = 1
startCommand = "/opt/keycloak/bin/kc.sh start-dev --db mysql --db-url-host $MYSQLHOST --db-username $MYSQLUSER --db-password $MYSQLPASSWORD --http-port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
